services:
  ds-2dgs:
    build:
      context: .
      dockerfile: Dockerfile.2dgs
    image: ds-2dgs
    container_name: ds-2dgs
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8888:8888"  # Jupyter Lab port mapping
    volumes:
      - ~/drivestudio:/workspace   # mount local repo
    working_dir: /workspace
    tty: true

# Build docker:
# docker compose -f Docker/docker-compose.2dgs.yml build

# Start the container:
# docker compose -f Docker/docker-compose.2dgs.yml up -d ds-2dgs

# Run the container (every time):
# docker exec -it ds-2dgs bash